# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_data_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('photolinks', models.CharField(max_length=1000)),
                ('videolinks', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('features', models.TextField()),
                ('milege', models.CharField(max_length=10)),
                ('Body_type', models.CharField(max_length=20)),
                ('specifications', models.TextField()),
                ('general_information', models.TextField()),
                ('dealer_number', models.IntegerField()),
                ('dealer_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Varient_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('varient_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('features', models.TextField()),
                ('milege', models.CharField(max_length=10)),
                ('Body_type', models.CharField(max_length=20)),
                ('specifications', models.TextField()),
                ('general_information', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car_data',
        ),
    ]
