# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0006_auto_20161015_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_data_old',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
