# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0007_auto_20161015_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_data_old',
            name='photolinks',
            field=models.FileField(null=True, upload_to='carsell/'),
        ),
    ]
