# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0008_auto_20161015_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_data_old',
            old_name='videolinks',
            new_name='videolink',
        ),
    ]
