# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0012_auto_20161016_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='varient_data',
            name='varient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
