# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0014_auto_20161017_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_data_old',
            name='photolinks',
            field=models.FileField(default='carsell/nocar.jpg', upload_to='carsell/'),
        ),
    ]
