# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0016_auto_20161017_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_data_new',
            name='features',
        ),
    ]
