# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0017_remove_car_data_new_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_data_new',
            name='price',
            field=models.IntegerField(),
        ),
    ]
