# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0019_auto_20161018_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient_data',
            name='milege',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
