# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
