# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('creationdate', models.DateTimeField()),
            ],
        ),
    ]
