# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=25)),
                ('vericode', models.CharField(max_length=100)),
                ('verified', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
