# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20161013_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='score',
        ),
    ]
