# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_auto_20161013_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
