# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_auto_20161014_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='photo',
            field=models.FileField(default=b'carsell/nouser.jpg', upload_to=b'carsell/'),
        ),
    ]
